### ISSUE TITLE
Is there a benchmark result?

### ISSUE THREAD

**Issue by jovany-wang** [begeekmyfriend/skiplist#9]

**Comment by begeekmyfriend** [comment]
Run xxx_test.c.

**Comment by jovany-wang** [comment]
Thanks. BTW, Is this able to get a higher performance than skiplist in Redis?

**Comment by begeekmyfriend** [comment]
I am afraid it hard to perform much better in order of magnitudes than Redis since the implementations are nearly the same. The small difference in my code is I am using double linked list and you can traverse in reverse. And the implementation without rank would run much faster than that with rank.
